name: Toolkit Checks
on:  
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * 1'

jobs:

  run-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 60  
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker-compose -h
        docker compose -h
        ls -la
        bash ./run-go-rpa-tests.sh Stop-Containers-And-Build-Docker-Container-With-Compose
    - name: Run the Docker container
      run: |
        ls -la
        bash ./run-go-rpa-tests.sh Run-Specific-Tests-Inside-Docker Start-Go-Language-Functional-Tests       