name: Toolkit Checks
on:  
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * 1'

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image and run the Docker container
      run: |
        docker build . --file Dockerfile.TestRunner -t test-runner
        #docker run -it --rm -v ${PWD}:/test --workdir /test test-runner /bin/bash ./run-go-rpa-tests.sh
        docker run -d --rm --name run-go-rpa-tests -v ${PWD}/run-go-rpa-tests.sh:/run-go-rpa-tests.sh test-runner /bin/bash -c ./run-go-rpa-tests.sh GitHub-CI-Tests-In-Docker       