name: Toolkit Checks
on:  
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * 1'

jobs:

  run-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 60  
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        ls -la
        docker build . --file Dockerfile.TestRunner -t test-runner
    - name: Run the Docker container
      run: |
        ls -la
        docker run --rm -v ${PWD}:/test --workdir /test test-runnertest-runner /bin/bash -c ./run-go-rpa-tests.sh GitHub-CI-Tests-In-Docker      